[package]
authors = ["David Irvine <david.irvine@maidsafe.net>"]
name = "neuroevolution"
version = "0.0.1"

[dependencies]
crossbeam = "~0.2.10"
num_cpus = "1.2.0"
rand = "~0.3.15"
rulinalg = "~0.3.7"

[dependencies.clippy]
optional = true
version = "~0.0.103"
